version: '3.8'

services:
  dynamo:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"  # DynamoDB local default port is 8000
    command: -jar DynamoDBLocal.jar -inMemory -sharedDb
    container_name: dynamo-local
    environment:
     AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
     AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
     REGION: 'eu-east-1'

  secrets_manager:
    image: skarpdev/aws-secrets-manager-emulator:0.1.0 ## remember to update the version
    volumes:
      - ./secrets:/secrets 
    ports:
      - "4567:3000"
    container_name: secrets-manager-local
