name: CM

on:
  workflow_dispatch:
  #schedule:
    #- cron: '0 5 * * *'      # Ejecuta todos los días a las 5:00 AM UTC

jobs:
  try-to-sing:
    runs-on: ubuntu-latest
    env:
      FQDN: https://diax.website
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Copy enviromental variables
        run: |
          cp apps/diax-canary/.env.template apps/diax-canary/.env

          #Replace if it exists or append if it doesn't
          sed -i 's/^COGNITO_TEST_PASSWORD=.*/COGNITO_TEST_PASSWORD=${{ secrets.COGNITO_TEST_PASSWORD }}/' apps/diax-canary/.env || echo "COGNITO_TEST_PASSWORD=${{ secrets.COGNITO_TEST_PASSWORD }}" >> apps/diax-canary/.env
          
      - name: Cache node_modules and Yarn cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
             yarn install --frozen-lockfile              
             yarn playwright install --with-deps

      #CANARY
      - name: Run diax-front e2e tests
        run: |
          yarn wait-on $FQDN 
          yarn nx run diax-canary:e2e

     
