name: CM

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'      # Ejecuta todos los días a las 5:00 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FQDN: https://diax.website
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install dependencies
        run: |
             yarn install --frozen-lockfile              
             yarn playwright install-deps

      #CANARY
      - name: Run diax-front e2e tests
        run: |
          yarn wait-on $FQDN 
          yarn nx run diax-canary:e2e

     
