name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      dynamo:
        image: amazon/dynamodb-local:latest
        ports:
          - 27017:27017

      cognito:
        image: jagregory/cognito-local
        ports:
          - 4566:4566

      secrets_manager:
        image: amazon/aws-secrets-manager-secret-adm-controller
        ports:
          - 4567:4567

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Yarn
        run: npm install -g yarn

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install dependencies
        run: |
             yarn install --frozen-lockfile 
             yarn playwright install-deps

      - name: Copy enviromental variables
        run: |
          cp apps/diax-back/.env.template apps/diax-back/.env
          cp apps/diax-back-e2e/.env.template apps/diax-back-e2e/.env
          cp apps/diax-front/.env.local.template apps/diax-front/.env.local
          cp apps/diax-front-e2e/.env.template apps/diax-front-e2e/.env

      #FRONTEND
      - name: Run diax-front lint
        run: yarn nx run diax-front:lint

      - name: Run diax-front unit tests
        run: yarn nx run diax-front:test --maxWorkers=2 --detectOpenHandles --forceExit

      - name: Run diax-front e2e tests
        run: |
          yarn nx run diax-front:serve & 
          SERVER_PID=$!
          yarn wait-on http://localhost:4000/ --timeout 30000
          yarn nx run diax-front-e2e:e2e
          kill $SERVER_PID

      #BACKEND
      - name: Run diax-back lint
        run: yarn nx run diax-back:lint

      - name: Run diax-back unit tests
        run: yarn nx run diax-back:test --maxWorkers=2 --detectOpenHandles --forceExit

      - name: Run diax-back e2e tests
        run: |
          yarn nx run diax-back:serve & 
          SERVER_PID=$!
          yarn wait-on http://localhost:3000/api --timeout 30000
          yarn nx run diax-back-e2e:e2e
          kill $SERVER_PID
