# .github/workflows/reusable-deploy.yml
name: Reusable Deploy

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      service:
        required: true
        type: string
      project:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 009160061988.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and push Docker image
        run: |
          sudo docker build -f apps/${{ inputs.project }}/Dockerfile -t 009160061988.dkr.ecr.us-east-1.amazonaws.com/diax-registry/${{ inputs.project }}:${{ inputs.tag }} --push .

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster diax-main --service ${{ inputs.service }} --force-new-deployment --no-cli-pager
